"""Agent class for LLM-driven autonomous systems.

Agents orchestrate LLMs with tools to reason, plan, and execute complex tasks.
They handle tool calling, error recovery, and maintain conversation context.
"""

from __future__ import annotations

import asyncio
import inspect
import json
import logging
from dataclasses import dataclass
from typing import Any, AsyncIterator, Callable, Dict, List, Optional

from .language_model import LanguageModel

logger = logging.getLogger(__name__)


@dataclass
class AgentResult:
    """Result from agent execution."""

    output: str
    metadata: Dict[str, Any]


@dataclass
class StreamEvent:
    """Event emitted during agent streaming."""

    type: str  # "thinking" | "tool_call" | "tool_result" | "response" | "error"
    content: Optional[str] = None
    tool_name: Optional[str] = None
    arguments: Optional[Dict[str, Any]] = None
    result: Optional[Any] = None
    error: Optional[str] = None


@dataclass
class AgentPlan:
    """Plan generated by agent for task execution."""

    steps: List[Dict[str, Any]]


class Agent:
    """High-level agent for autonomous LLM-driven task execution.

    Agents orchestrate LLMs with tools to reason, plan, and execute complex tasks.
    They handle tool calling, error recovery, and maintain conversation context.

    Example:
        ```python
        lm = LanguageModel()
        agent = Agent(
            name="assistant",
            model=lm,
            instructions="You are a helpful assistant.",
            tools=[search_tool, calculator_tool]
        )

        result = await agent.run("What is 2+2 and search for AI news")
        ```
    """

    def __init__(
        self,
        name: str,
        model: LanguageModel,
        instructions: Optional[str] = None,
        tools: Optional[List[Any]] = None,
        session: Optional[Any] = None,  # Session type
        memory: Optional[Any] = None,  # Memory type
        max_iterations: int = 10,
    ):
        """Create an Agent instance.

        Args:
            name: Agent identifier
            model: LanguageModel instance for LLM interactions
            instructions: System instructions defining agent behavior
            tools: List of Tool instances or @tool-decorated functions
            session: Optional Session for conversation context
            memory: Optional Memory for long-term knowledge
            max_iterations: Maximum reasoning iterations (default: 10)
        """
        self.name = name
        self.model = model
        self.instructions = instructions or f"You are {name}, a helpful AI assistant."
        self.tools = tools or []
        self.session = session
        self.memory = memory
        self.max_iterations = max_iterations

        # Build tool map for quick lookup
        self._tool_map: Dict[str, Callable] = {}
        for tool in self.tools:
            tool_name = self._get_tool_name(tool)
            tool_handler = self._get_tool_handler(tool)
            if tool_name and tool_handler:
                self._tool_map[tool_name] = tool_handler

        logger.info(
            f"Initialized agent '{name}' with {len(self.tools)} tools, "
            f"max_iterations={max_iterations}"
        )

    def _get_tool_name(self, tool: Any) -> Optional[str]:
        """Extract tool name from tool object or function."""
        # Check if it's a Tool instance
        if hasattr(tool, "name"):
            return tool.name

        # Check if it's a @tool-decorated function
        if hasattr(tool, "_tool_name"):
            return tool._tool_name

        # Use function name as fallback
        if callable(tool):
            return tool.__name__

        return None

    def _get_tool_handler(self, tool: Any) -> Optional[Callable]:
        """Extract callable handler from tool object or function."""
        # If it's a Tool instance with handler attribute
        if hasattr(tool, "handler") and callable(tool.handler):
            return tool.handler

        # If it's a callable (function or @tool-decorated)
        if callable(tool):
            return tool

        return None

    def _build_tool_schemas(self) -> List[Dict[str, Any]]:
        """Build tool schemas for LLM."""
        schemas = []

        for tool in self.tools:
            tool_name = self._get_tool_name(tool)
            if not tool_name:
                continue

            schema = {"name": tool_name, "description": "", "input_schema": {}}

            # Extract description
            if hasattr(tool, "_tool_description"):
                schema["description"] = tool._tool_description
            elif hasattr(tool, "description"):
                schema["description"] = tool.description
            elif hasattr(tool, "__doc__") and tool.__doc__:
                schema["description"] = tool.__doc__.strip().split("\n")[0]

            # Extract input schema
            if hasattr(tool, "_tool_input_schema"):
                schema["input_schema"] = tool._tool_input_schema
            elif hasattr(tool, "input_schema"):
                schema["input_schema"] = tool.input_schema

            schemas.append(schema)

        return schemas

    async def run(self, prompt: str, session: Optional[Any] = None) -> AgentResult:
        """Execute agent with given prompt.

        Args:
            prompt: User request/query string
            session: Optional Session override

        Returns:
            AgentResult with output and metadata

        Raises:
            RuntimeError: If agent fails to complete task
        """
        effective_session = session or self.session
        messages = []

        # Add system instructions
        if self.instructions:
            messages.append({"role": "system", "content": self.instructions})

        # Add session history if available
        if effective_session and hasattr(effective_session, "history"):
            try:
                history = await effective_session.history()
                messages.extend(history)
            except Exception as e:
                logger.warning(f"Failed to load session history: {e}")

        # Add user prompt
        messages.append({"role": "user", "content": prompt})

        # Build tool schemas
        tool_schemas = self._build_tool_schemas() if self.tools else None

        # Execute with iteration limit
        iteration = 0
        while iteration < self.max_iterations:
            iteration += 1

            # Call LLM
            try:
                response = await self.model.generate(prompt=messages, tools=tool_schemas)
            except Exception as e:
                logger.error(f"LLM call failed: {e}")
                raise RuntimeError(f"Agent LLM call failed: {e}")

            # Extract response content
            content = response.content if hasattr(response, "content") else str(response)

            # Check for tool calls
            tool_calls = self._extract_tool_calls(response)

            if not tool_calls:
                # No tool calls - agent is done
                result = AgentResult(
                    output=content, metadata={"iterations": iteration, "tool_calls_made": 0}
                )

                # Save to session if available
                if effective_session:
                    try:
                        await effective_session.send_message(
                            {"role": "assistant", "content": content}
                        )
                    except Exception as e:
                        logger.warning(f"Failed to save to session: {e}")

                return result

            # Execute tool calls
            tool_results = []
            for tool_call in tool_calls:
                tool_name = tool_call.get("name")
                tool_args = tool_call.get("arguments", {})

                if tool_name not in self._tool_map:
                    logger.warning(f"Tool '{tool_name}' not found")
                    tool_results.append(
                        {"tool": tool_name, "error": f"Tool '{tool_name}' not found"}
                    )
                    continue

                try:
                    handler = self._tool_map[tool_name]
                    result = handler(**tool_args)

                    # Handle async tools
                    if inspect.iscoroutine(result) or inspect.isawaitable(result):
                        result = await result

                    tool_results.append({"tool": tool_name, "result": result})
                except Exception as e:
                    logger.error(f"Tool '{tool_name}' failed: {e}")
                    tool_results.append({"tool": tool_name, "error": str(e)})

            # Add assistant message and tool results to conversation
            messages.append({"role": "assistant", "content": content, "tool_calls": tool_calls})
            messages.append({"role": "tool", "content": json.dumps(tool_results)})

        # Max iterations reached
        raise RuntimeError(
            f"Agent exceeded maximum iterations ({self.max_iterations}) without completing task"
        )

    async def stream(
        self, prompt: str, session: Optional[Any] = None
    ) -> AsyncIterator[StreamEvent]:
        """Stream agent execution events.

        Args:
            prompt: User request/query string
            session: Optional Session override

        Yields:
            StreamEvent objects as agent executes

        Example:
            ```python
            async for event in agent.stream("Complex task"):
                if event.type == "tool_call":
                    print(f"Calling {event.tool_name}")
            ```
        """
        # TODO: Implement proper streaming with model streaming support
        # For now, yield a single result event
        yield StreamEvent(type="thinking", content="Processing request...")

        try:
            result = await self.run(prompt, session)
            yield StreamEvent(type="response", content=result.output)
        except Exception as e:
            yield StreamEvent(type="error", error=str(e))

    def plan(self, prompt: str) -> AgentPlan:
        """Generate execution plan for prompt (without executing).

        Args:
            prompt: User request/query string

        Returns:
            AgentPlan with steps

        Note:
            This is a synchronous planning method that doesn't execute tools.
        """
        # Simple heuristic planning - can be enhanced with LLM-based planning
        steps = [
            {"type": "reasoning", "description": "Analyze request and determine approach"},
            {"type": "execution", "description": "Execute necessary tools and computations"},
            {"type": "synthesis", "description": "Synthesize results into final response"},
        ]

        return AgentPlan(steps=steps)

    def _extract_tool_calls(self, response: Any) -> List[Dict[str, Any]]:
        """Extract tool calls from LLM response.

        Args:
            response: Response from LanguageModel

        Returns:
            List of tool call dictionaries
        """
        # Check if response has tool_calls attribute
        if hasattr(response, "tool_calls") and response.tool_calls:
            return response.tool_calls

        # Check for structured tool calls in content
        # This is model-specific and may need enhancement

        return []


__all__ = [
    "Agent",
    "AgentResult",
    "StreamEvent",
    "AgentPlan",
]
